modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Artemka091102/Navigation/issues"
[[mods]]
modId="Navigation"
version="${file.jarVersion}"
displayName="Navigation"
updateJSONURL="https://raw.githubusercontent.com/Artemka091102/Navigation/master/src/main/resources/META-INF/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/Navigation"
logoFile="Navigation.png"
credits='''
'''
authors='''

Artemka091102
'''
description='''
This mod makes navigation more realistic. Write your questions @Artemka091102#6675
'''
[[dependencies.Navigation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13,1.15.2]"
    ordering="NONE"
    side="BOTH"
